name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: coursier/cache-action@v7
    - name: Set up JDK 11
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt clean test IntegrationTest/test
  merge:
    name: Merge dependency update
    if: ${{ github.actor == 'scala-steward' || github.actor == 'scala-steward[bot]' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: merge PR
        uses: desbo/merge-pr-action@v0
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.PR_MERGE_PAT }}
        with:
          GITHUB_TOKEN: ${{ secrets.PR_MERGE_PAT }}
          ALLOWED_UPDATE: minor
          MERGE_METHOD: squash
